### ISSUE TITLE
Absolute session path requires manually creating missing dirs

### ISSUE THREAD

**Issue by tranzystorekk** [natecraddock/sessions.nvim#10]
My `sessions` configurations contains an absolute path:

```lua
session_filepath = vim.fn.stdpath("data") .. "/sessions",
absolute = true,
```

which doesn't exist in a fresh neovim setup. Without manual intervention, triggering configured events results in `sessions` erroring out, complaining about `Cannot open <session file> for writing`.

Arguably this is a common setup for working with `sessions`, and I'd like to discuss possible fixes:

- automatically mkdir `session_filepath`, this is a nuclear solution and while for dirs within the datapath it's reasonable, it's hard to anticipate the many ways where it would be undesirable
- warn the user that the directory needs to exist, then halt any further plugin action

**Comment by natecraddock** [comment]
Sorry for the delay here. I'm not using this plugin anymore. Feel free to fix this however you see best!

You have commit access. I trust your judgement, it seems like you have already thought of possible solutions. Both seem reasonable to me!

**Comment by tranzystorekk** [comment]
Resolved in https://github.com/natecraddock/sessions.nvim/commit/f13158483e0b6255c6dfe473145ce4ee3495d844

Ultimately if `absolute = true` I don't see any reasonable case where the directory shouldn't be automatically created 😁

**Comment by natecraddock** [comment]
Looks good, thanks!
