### ISSUE TITLE
Deleted buffer is loaded when `require('sessions').load`

### ISSUE THREAD

**Issue by Jaehaks** [natecraddock/sessions.nvim#12]
Thank you for your efforts.

I loaded 4 buffers and removed 1 buffers from list.
The removed 1 buffer is listed also as $argadd in `session_filepath` file. 
![image](https://github.com/user-attachments/assets/5701b217-7e13-4dcb-9c52-299b5ebeb4be)
I guess it is related with why the removed 1 buffer is loaded when I call `load()` function.

I called `sessions.save` when Vim Leaves like this
```lua
vim.api.nvim_create_autocmd('VimLeavePre', {
	group = User_augroup,
	pattern = '*',
	callback = function ()
		sessions.save(saved_path, {autosave = false})
	end
})
```

Is this working normally?

**Comment by natecraddock** [comment]
Hey! sessions.nvim is only a thin wrapper around `:mksession`, so any behavior in saving a session with `:mksession` will be used.

You can take a look at `:h sessionoptions` to see if there are any configurations that can help you customize what buffers to keep!
