### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/sessions.nvim#3]
Hi! I hope you are all doing well!

I no longer use Neovim regularly, but I really would like to keep this plugin alive. It's been really simple to maintain, but I worry about the long-term.

So I'm looking for someone willing to step in and maintain this plugin. Either
1. Someone who is willing to fork and create the new official project or
2. Someone who wants to co-maintain the project

I think the second is the simplest, and no one has to update their configs to point to a new repository.

**If no one steps up, I will try my best to make sure this works for as long as possible.** But I won't make any promises. If a future Neovim release would cause an unreasonable amount of work for me to update this plugin, I probably wouldn't update it.

Sorry if that's sad news for anyone, and I apologize if this breaks someone's workflow someday. I don't think this plugin will stop working anytime soon, but if it does... 😬

**Comment by awerebea** [comment]
> I no longer use Neovim regularly

Just curious, which editor did you switch to?

**Comment by natecraddock** [comment]
I switched back to VSCode.

The short story is everyone on my team at work uses VSCode and it's easier to standardize some of our tooling (like Docker dev containers) that way.

Long(er) story is that after using Neovim+emacs full time for 1.5 years I learned a lot about modal text editing and editor extensibility. I found a lot that I love. [I also learned that I prefer a GUI over terminals for editing and navigating code](https://nathancraddock.com/blog/2022/thoughts-on-vim-terminals-gui/). So that was also part of my motivation to jump back.

**Comment by awerebea** [comment]
> [I also learned that I prefer a GUI over terminals for editing and navigating code](https://nathancraddock.com/blog/2022/thoughts-on-vim-terminals-gui/).

Very interesting article, thanks!

**Comment by natecraddock** [comment]
@awerebea haha glad you enjoyed my ramblings :)

**Comment by danielo515** [comment]
Just read your article, and I can feel your pain. I'm in the same exact situation: I love editing in neovim, I love how easy is to add new extensions (commands, binds, functionality in general) but when I need to read, understand and navigate code I really like to be away from the keyboard, in a relaxed position with my wireless track point in my hand, just reading, not typing.
While reading your article I was: man, you're describing Onivim 2. But I see that you already know it (I was a baker) so nothing to explain you there. I was really sad that the developer has to stop working on it .
Wish you find our dreamed editor,and when you do, please let us know

**Comment by StitiFatah** [comment]
> Just read your article, and I can feel your pain. I'm in the same exact situation: I love editing in neovim, I love how easy is to add new extensions (commands, binds, functionality in general) but when I need to read, understand and navigate code I really like to be away from the keyboard, in a relaxed position with my wireless track point in my hand, just reading, not typing. While reading your article I was: man, you're describing Onivim 2. But I see that you already know it (I was a baker) so nothing to explain you there. I was really sad that the developer has to stop working on it . Wish you find our dreamed editor,and when you do, please let us know

I mean these days we can do that pretty easily with neovim, we can use the mouse to scroll, copy, past, select or whatever, being for a regular file or even in a file tree like neotree. 

I must admit I'm the tiling windows manager type of user the OP describes (and I really do believe it's way more efficient than any DE/floating wm based workflow ( and I've naturally used those for years) + it's ten times easier to configure i3 than turning Neovim into (even a semi) IDE ) but I feel like the current mouse support and some extensions like which-key.nvim make "casual" browsing a breeze.

**Comment by danielo515** [comment]
> but I feel like the current mouse support and some extensions like which-key.nvim make "casual" browsing a breeze.

It's full of gotchas though, and the range of actions is very limited. On top of that, there is a lot of contextual information that you only care in certain very specific areas, and GUIs are great to give you that contextual data, and even more important, actions. For example I not only want to see the filetype in the bottom bar, I also want to be able to change it by just clicking on it. I don't want to have to reach the keyboard to see a definition, I sometimes just want to hover my mouse. I want to be able to right-click a tab and reveal it in sidebar, finder or some other option. I want to re-arrange entire layouts with the mouse, not only resize, but move to left, bottom, etc. I also want to be able to do all that with the keyboard, sure, but when there is no need for me to remember a key-combination or command I want the GUI to be there to give me the support I'm missing.

**Comment by tranzystorekk** [comment]
Hi @natecraddock if you are still interested in a maintainer I'd be willing to help out!

I was looking to largely simplify my session management logic and browsing the current session plugin landscape, most either do too much, lack any API or are aimed for a much different workflow than mine. `sessions` turned out pretty much perfect :)

I'm not sure what kind of help you are expecting, but I agree with the current vision of `sessions` (no automagic, simple API and scope etc.)

**Comment by natecraddock** [comment]
Hey @tranzystorek-io thank you for expressing interest in helping! I just added you as a collaborator on the repo. My main motivation for this is just to make sure someone who uses the plugin more regularly than me to have access.

And I'm happy to hear sessions is nearly perfect for you! If you have any ideas/suggestions feel free to make issues and discuss them with me
