### ISSUE TITLE
Make start_autosave public

### ISSUE THREAD

**Issue by tranzystorekk** [natecraddock/sessions.nvim#5]
A quick rationale coming straight from my current session config. I want any new directory I open to automatically register as a session. At the moment it requires doing a manual save if a load fails:

```lua
vim.api.nvim_create_autocmd('VimEnter', {
  callback = function (data)
    local is_directory = vim.fn.isdirectory(data.file) == 1
    if not is_directory then
      return
    end

    vim.cmd.cd(data.file)

    local sessions_api = require('sessions')
    local session_found = sessions_api.load(nil, { silent = true })
    -- currently this is the way to start a new session if none was detected
    if not session_found then
      sessions_api.save()
    end

    -- other code omitted
  end,
})

```

If the `sessions.start_autosave` function was public (after a small refactoring to separate off writing session files), it would be slightly more convenient bc the user can delay the first save to an actual event like `WinEnter`.

On the other hand this might feel nitpicky, and I don't want to introduce new API if it feels unnecessary.

**Comment by natecraddock** [comment]
I'm okay with this! I didn't look too closely, but it would probably be easy to pass a table to `start_autosave` with an option to skip saving the file.

Do you want to work on this?

**Comment by tranzystorekk** [comment]
Sure, I'll post a PR soonish :)
