### ISSUE TITLE
Feature request: Save QF list

### ISSUE THREAD

**Issue by neonvoidx** [natecraddock/sessions.nvim#9]
is there anyway to save quickfix list when saving session?

**Comment by tranzystorekk** [comment]
AFAIK there is no option in `sessionoptions` to save quickfix, and `sessions` is only a thin wrapper around `:mksession`

**Comment by neonvoidx** [comment]
ah ok, no worries

**Comment by natecraddock** [comment]
I do recall seeing an alternative plugin for session saving that does _not_ use `:mksession` but I can't find it now. If you can find it, then maybe that could be a solution if it implements saving the quickfix

**Comment by jacobrreed** [comment]
https://github.com/ten3roberts/qf.nvim this has the ability to save and load QF lists

**Comment by neonvoidx** [comment]
https://github.com/ten3roberts/qf.nvim/blob/main/lua%2Fqf.lua#L656-L665
Has the ability to save and load quick fix. Maybe that's a good place to copy

**Comment by natecraddock** [comment]
I'm not planning on adding any new major features to sessions.nvim. I hope you can find something to help you though!
